export declare const AuditAction: {
    readonly LOGIN_SUCCESS: "LOGIN_SUCCESS";
    readonly LOGIN_FAILED: "LOGIN_FAILED";
    readonly REGISTER: "REGISTER";
    readonly LOGOUT: "LOGOUT";
    readonly REFRESH_TOKEN: "REFRESH_TOKEN";
    readonly BOOKING_CREATED: "BOOKING_CREATED";
    readonly BOOKING_CONFIRMED: "BOOKING_CONFIRMED";
    readonly BOOKING_CANCELLED: "BOOKING_CANCELLED";
    readonly BOOKING_EXPIRED: "BOOKING_EXPIRED";
    readonly BOOKING_REFUNDED: "BOOKING_REFUNDED";
    readonly SEAT_HELD: "SEAT_HELD";
    readonly SEAT_RELEASED: "SEAT_RELEASED";
    readonly SEAT_BOOKED: "SEAT_BOOKED";
    readonly SEAT_STATUS_CHANGED: "SEAT_STATUS_CHANGED";
    readonly PAYMENT_CREATED: "PAYMENT_CREATED";
    readonly PAYMENT_SUCCESS: "PAYMENT_SUCCESS";
    readonly PAYMENT_FAILED: "PAYMENT_FAILED";
    readonly PAYMENT_REFUNDED: "PAYMENT_REFUNDED";
    readonly PAYMENT_AUTO_REFUNDED_AFTER_HOLD_EXPIRY: "PAYMENT_AUTO_REFUNDED_AFTER_HOLD_EXPIRY";
    readonly PAYMENT_AUTO_REFUND_FAILED: "PAYMENT_AUTO_REFUND_FAILED";
    readonly COUPON_APPLIED: "COUPON_APPLIED";
    readonly COUPON_REDEEMED: "COUPON_REDEEMED";
    readonly CREDITS_REDEEMED: "CREDITS_REDEEMED";
    readonly CREDITS_EARNED: "CREDITS_EARNED";
    readonly BUS_CREATED: "BUS_CREATED";
    readonly BUS_UPDATED: "BUS_UPDATED";
    readonly BUS_DELETED: "BUS_DELETED";
    readonly ROUTE_CREATED: "ROUTE_CREATED";
    readonly ROUTE_UPDATED: "ROUTE_UPDATED";
    readonly ROUTE_DELETED: "ROUTE_DELETED";
    readonly SCHEDULE_CREATED: "SCHEDULE_CREATED";
    readonly SCHEDULE_UPDATED: "SCHEDULE_UPDATED";
    readonly SCHEDULE_CANCELLED: "SCHEDULE_CANCELLED";
    readonly USER_ROLE_CHANGED: "USER_ROLE_CHANGED";
    readonly USER_BLOCKED: "USER_BLOCKED";
    readonly USER_UNBLOCKED: "USER_UNBLOCKED";
};
export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
export declare const AuditEntityType: {
    readonly USER: "USER";
    readonly BOOKING: "BOOKING";
    readonly SEAT: "SEAT";
    readonly PAYMENT: "PAYMENT";
    readonly COUPON: "COUPON";
    readonly LOYALTY: "LOYALTY";
    readonly BUS: "BUS";
    readonly ROUTE: "ROUTE";
    readonly SCHEDULE: "SCHEDULE";
};
export type AuditEntityTypeValue = (typeof AuditEntityType)[keyof typeof AuditEntityType];
//# sourceMappingURL=actions.d.ts.map