export const AuditAction = {
  // Auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  REGISTER: "REGISTER",
  LOGOUT: "LOGOUT",
  REFRESH_TOKEN: "REFRESH_TOKEN",

  // Booking
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_EXPIRED: "BOOKING_EXPIRED",
  BOOKING_REFUNDED: "BOOKING_REFUNDED",

  // Seats
  SEAT_HELD: "SEAT_HELD",
  SEAT_RELEASED: "SEAT_RELEASED",
  SEAT_BOOKED: "SEAT_BOOKED",
  SEAT_STATUS_CHANGED: "SEAT_STATUS_CHANGED",

  // Payments
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",

  // Coupons
  COUPON_APPLIED: "COUPON_APPLIED",
  COUPON_REDEEMED: "COUPON_REDEEMED",

  // Loyalty
  CREDITS_REDEEMED: "CREDITS_REDEEMED",
  CREDITS_EARNED: "CREDITS_EARNED",

  // Admin
  BUS_CREATED: "BUS_CREATED",
  BUS_UPDATED: "BUS_UPDATED",
  BUS_DELETED: "BUS_DELETED",
  ROUTE_CREATED: "ROUTE_CREATED",
  ROUTE_UPDATED: "ROUTE_UPDATED",
  ROUTE_DELETED: "ROUTE_DELETED",
  SCHEDULE_CREATED: "SCHEDULE_CREATED",
  SCHEDULE_UPDATED: "SCHEDULE_UPDATED",
  SCHEDULE_CANCELLED: "SCHEDULE_CANCELLED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_BLOCKED: "USER_BLOCKED",
  USER_UNBLOCKED: "USER_UNBLOCKED",
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
  USER: "USER",
  BOOKING: "BOOKING",
  SEAT: "SEAT",
  PAYMENT: "PAYMENT",
  COUPON: "COUPON",
  LOYALTY: "LOYALTY",
  BUS: "BUS",
  ROUTE: "ROUTE",
  SCHEDULE: "SCHEDULE",
} as const;

export type AuditEntityTypeValue =
  (typeof AuditEntityType)[keyof typeof AuditEntityType];
